<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.28">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>blog</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js" integrity="sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2" crossorigin="anonymous"></script><script src="blog_files/libs/clipboard/clipboard.min.js"></script>
<script src="blog_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="blog_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="blog_files/libs/quarto-html/popper.min.js"></script>
<script src="blog_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="blog_files/libs/quarto-html/anchor.min.js"></script>
<link href="blog_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="blog_files/libs/quarto-html/quarto-syntax-highlighting-49e51e44f424ea8c7044b429bdbbbfe2.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="blog_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="blog_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="blog_files/libs/bootstrap/bootstrap-138a6193a3bd40baf1e627da441a4734.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script src="https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js" integrity="sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>


</head>

<body class="fullcontent quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">




<section id="which-u.s.-equity-sectors-really-behaved-differently-in-the-last-decade-and-a-half" class="level1">
<h1>Which U.S. Equity Sectors Really Behaved Differently in the Last Decade and a Half?</h1>
<p>Word count: xxxx words</p>
<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">Introduction</h2>
<p>Investors often talk about equity sectors as if their differences are obvious and predictable. Technology is often associated with rapid growth, utilities with stability, and energy with strong cycles. But investing in equity sectors is about more than just identifying which sector has the best return. Considering factors like how volatile sectors are, how they move with each other, and how sensitive they are to movements in the market is equally, if not more important.</p>
<p>This blog examines whether major U.S. equity sectors really behaved differently over time. Using daily ETF data from 1st of January 2010, to 31st of December 2025, I will look at four main dimensions: long-run returns, volatility, correlation, and market beta. The goal is to understand if any sectors offered any meaningfully different investment profiles over the period, and to see what the trends have been.</p>
</section>
<section id="data" class="level2">
<h2 class="anchored" data-anchor-id="data">Data</h2>
<p>The analysis uses daily adjusted price data for 8 major sector ETFs, as well as for SPY, the benchmark of this analysis. The sample covers a range of 15 years, giving a long time frame that includes both stable periods and some more volatile periods like the COVID 19 pandemic. To keep the comparison consistent, all the ETFs are sourced from the <a href="https://www.ssga.com/us/en/intermediary/capabilities/equities/sector-investing/sector-and-industry-etfs"><strong>State Street SPDR Family</strong></a>. Therefore, each ETF represents a specific part of the U.S. equity market within the same general fund structure.<br>
</p>
<p>Daily adjusted prices are converted into returns and then used to compare sectors across the four dimensions mentioned. This allows the analysis to go beyond simple return comparisons and examine whether sectors offered meaningfully different investment profiles over time.<br>
</p>
<p><strong>The following table gives an overview of what each ticker stands for:</strong></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Ticker</th>
<th>Sector or Benchmark</th>
<th>Role in the analysis</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>SPY</td>
<td>S&amp;P 500 ETF</td>
<td>Benchmark</td>
</tr>
<tr class="even">
<td>XLK</td>
<td>Technology</td>
<td>Sector ETF</td>
</tr>
<tr class="odd">
<td>XLF</td>
<td>Financial</td>
<td>Sector ETF</td>
</tr>
<tr class="even">
<td>XLV</td>
<td>Health Care</td>
<td>Sector ETF</td>
</tr>
<tr class="odd">
<td>XLE</td>
<td>Energy</td>
<td>Sector ETF</td>
</tr>
<tr class="even">
<td>XLY</td>
<td>Consumer Discretionary</td>
<td>Sector ETF</td>
</tr>
<tr class="odd">
<td>XLU</td>
<td>Utilities</td>
<td>Sector ETF</td>
</tr>
<tr class="even">
<td>XLP</td>
<td>Consumer Staples</td>
<td>Sector ETF</td>
</tr>
<tr class="odd">
<td>XLB</td>
<td>Materials</td>
<td>Sector ETF</td>
</tr>
</tbody>
</table>
<p>Each ticker is the market symbol for an ETF. SPY is included as the benchmark because it tracks the broader U.S. stock market, while the remaining tickers represent major sector ETFs from the same SPDR family, allowing for a more consistent comparison across sectors.</p>
</section>
<section id="workflow-and-methodology" class="level2">
<h2 class="anchored" data-anchor-id="workflow-and-methodology">Workflow and Methodology</h2>
<p>The project follows a clear and replicable workflow. Daily price data for SPY and the sector ETFs were first collected and stored as separate raw CSV files. These raw files were then cleaned, combined, and transformed into daily returns, which form the basis of the analysis.<br>
</p>
<p>Using these returns, the project generates summary statistics and visual outputs to compare sectors across performance, volatility, and correlation. To extend the analysis beyond descriptive comparisons, I also estimated sector betas relative to SPY as the market benchmark. This creates a transparent workflow that goes from raw data to cleaned data, descriptive evidence, and regression-based measures of market exposure.</p>
</section>
<section id="results-and-interpretation" class="level2">
<h2 class="anchored" data-anchor-id="results-and-interpretation">Results and interpretation</h2>
<section id="long-run-returns" class="level3">
<h3 class="anchored" data-anchor-id="long-run-returns">Long-run returns</h3>
<p>A natural way to start the comparison of these sectors is to compare their performance over the period. Cumulative returns show how performance evolved over the last 15 years and the percentage increase since the start. This makes it easy to identify sectors with strong long-run results and how even or uneven their performance was.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="output/figures/cumulative_returns.png" class="img-fluid figure-img"></p>
<figcaption>Cumulative returns of SPY and major U.S. sector ETFs, 2010 to 2025.</figcaption>
</figure>
</div>
<p>The figure shows that sector performance differed substantially over time. Technology (XLK) was by far the strongest performer, ending the sample with cumulative returns of more than 1400% and finishing well above all other sectors. Consumer Discretionary (XLY) also performed strongly and outpaced the broader market for most of the period, ending at roughly 900%. SPY, which serves as the benchmark, also delivered strong long-run growth, but remained clearly below the two best-performing sectors. By contrast, Energy (XLE) was the weakest performer. Its returns were much lower than the rest of the sample, only ending with a 190% cumulative return over 15 years, and it was notably more fragile, with a prolonged period of weakness between 2015 and 2020, even going negative briefly.<br>
</p>
<p>The differences in behavior became more visible after 2020 and COVID-19. To analyse this further, the next figure focuses on the Covid period and the aftermath</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="output/figures/cumulative_returns_covid.png" class="img-fluid figure-img"></p>
<figcaption>Cumulative returns of SPY and major U.S. sector ETFs during the COVID-19 pandemic.</figcaption>
</figure>
</div>
<p>One important note is that the cumulative return series here begins in 2020. This means the chart should be read as performance relative to the start of the pandemic period, rather than over the full sample.<br>
</p>
<p>This closer view amplifies the differences that are already visible in the full view. While all sectors suffered from the initial pandemic shock, the scale of decline and the speed of the recovery varied largely. Energy (XLE) experienced the sharpest fall and remained with negative returns for much longer than the rest, it only moved back into positive cumulative return around the beginning of 2020. On the other side, Technology (XLK) recovered much quicker and only had a small drop after the shock. Post-COVID, it produced the strongest performance. Consumer Discretionary (XLY) also rebounded strongly and remained one of the better-performing sectors throughout the recovery. One of the most interesting patterns I discovered is that, despite suffering the deepest early losses, Energy eventually finished the period with the second-highest cumulative return. Utilities (XLU), in contrast, stayed one of the weakest sectors throughout. It followed a much flatter recovery path and ended the period well below the stronger growth sectors as well as the benchmark.<br>
</p>
<p>Although cumulative return is a useful comparison, it does not show the full picture. It doesn’t show how much risk investors faced along the way, which is why we will look at volatility next.</p>
</section>
<section id="volatility" class="level3">
<h3 class="anchored" data-anchor-id="volatility">Volatility</h3>
<p>To understand sector differences more fully, it is useful to compare return and volatility together.</p>
<section id="summary-statistic-table" class="level4">
<h4 class="anchored" data-anchor-id="summary-statistic-table">Summary Statistic Table</h4>
<div id="dd03011f" class="cell" data-execution_count="1">
<div class="cell-output cell-output-display" data-execution_count="5">
<style type="text/css">
</style>

<table id="T_31fd7" class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th id="T_31fd7_level0_col0" class="col_heading level0 col0" data-quarto-table-cell-role="th">Ticker</th>
<th id="T_31fd7_level0_col1" class="col_heading level0 col1" data-quarto-table-cell-role="th">Mean Daily Return (%)</th>
<th id="T_31fd7_level0_col2" class="col_heading level0 col2" data-quarto-table-cell-role="th">Volatility (Std Dev)</th>
<th id="T_31fd7_level0_col3" class="col_heading level0 col3" data-quarto-table-cell-role="th">Worst Daily Return (%)</th>
<th id="T_31fd7_level0_col4" class="col_heading level0 col4" data-quarto-table-cell-role="th">Best Daily Return (%)</th>
<th id="T_31fd7_level0_col5" class="col_heading level0 col5" data-quarto-table-cell-role="th">Total Observations</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td id="T_31fd7_row0_col0" class="data row0 col0">SPY</td>
<td id="T_31fd7_row0_col1" class="data row0 col1">0.058</td>
<td id="T_31fd7_row0_col2" class="data row0 col2">1.084</td>
<td id="T_31fd7_row0_col3" class="data row0 col3">-10.942</td>
<td id="T_31fd7_row0_col4" class="data row0 col4">10.502</td>
<td id="T_31fd7_row0_col5" class="data row0 col5">4022</td>
</tr>
<tr class="even">
<td id="T_31fd7_row1_col0" class="data row1 col0">XLB</td>
<td id="T_31fd7_row1_col1" class="data row1 col1">0.042</td>
<td id="T_31fd7_row1_col2" class="data row1 col2">1.311</td>
<td id="T_31fd7_row1_col3" class="data row1 col3">-11.008</td>
<td id="T_31fd7_row1_col4" class="data row1 col4">11.760</td>
<td id="T_31fd7_row1_col5" class="data row1 col5">4022</td>
</tr>
<tr class="odd">
<td id="T_31fd7_row2_col0" class="data row2 col0">XLE</td>
<td id="T_31fd7_row2_col1" class="data row2 col1">0.038</td>
<td id="T_31fd7_row2_col2" class="data row2 col2">1.718</td>
<td id="T_31fd7_row2_col3" class="data row2 col3">-20.141</td>
<td id="T_31fd7_row2_col4" class="data row2 col4">16.037</td>
<td id="T_31fd7_row2_col5" class="data row2 col5">4022</td>
</tr>
<tr class="even">
<td id="T_31fd7_row3_col0" class="data row3 col0">XLF</td>
<td id="T_31fd7_row3_col1" class="data row3 col1">0.055</td>
<td id="T_31fd7_row3_col2" class="data row3 col2">1.383</td>
<td id="T_31fd7_row3_col3" class="data row3 col3">-13.709</td>
<td id="T_31fd7_row3_col4" class="data row3 col4">13.157</td>
<td id="T_31fd7_row3_col5" class="data row3 col5">4022</td>
</tr>
<tr class="odd">
<td id="T_31fd7_row4_col0" class="data row4 col0">XLK</td>
<td id="T_31fd7_row4_col1" class="data row4 col1">0.078</td>
<td id="T_31fd7_row4_col2" class="data row4 col2">1.369</td>
<td id="T_31fd7_row4_col3" class="data row4 col3">-13.814</td>
<td id="T_31fd7_row4_col4" class="data row4 col4">13.426</td>
<td id="T_31fd7_row4_col5" class="data row4 col5">4022</td>
</tr>
<tr class="even">
<td id="T_31fd7_row5_col0" class="data row5 col0">XLP</td>
<td id="T_31fd7_row5_col1" class="data row5 col1">0.041</td>
<td id="T_31fd7_row5_col2" class="data row5 col2">0.864</td>
<td id="T_31fd7_row5_col3" class="data row5 col3">-9.396</td>
<td id="T_31fd7_row5_col4" class="data row5 col4">8.511</td>
<td id="T_31fd7_row5_col5" class="data row5 col5">4022</td>
</tr>
<tr class="odd">
<td id="T_31fd7_row6_col0" class="data row6 col0">XLU</td>
<td id="T_31fd7_row6_col1" class="data row6 col1">0.045</td>
<td id="T_31fd7_row6_col2" class="data row6 col2">1.102</td>
<td id="T_31fd7_row6_col3" class="data row6 col3">-11.358</td>
<td id="T_31fd7_row6_col4" class="data row6 col4">12.793</td>
<td id="T_31fd7_row6_col5" class="data row6 col5">4022</td>
</tr>
<tr class="even">
<td id="T_31fd7_row7_col0" class="data row7 col0">XLV</td>
<td id="T_31fd7_row7_col1" class="data row7 col1">0.052</td>
<td id="T_31fd7_row7_col2" class="data row7 col2">1.019</td>
<td id="T_31fd7_row7_col3" class="data row7 col3">-9.861</td>
<td id="T_31fd7_row7_col4" class="data row7 col4">7.706</td>
<td id="T_31fd7_row7_col5" class="data row7 col5">4022</td>
</tr>
<tr class="odd">
<td id="T_31fd7_row8_col0" class="data row8 col0">XLY</td>
<td id="T_31fd7_row8_col1" class="data row8 col1">0.065</td>
<td id="T_31fd7_row8_col2" class="data row8 col2">1.281</td>
<td id="T_31fd7_row8_col3" class="data row8 col3">-12.669</td>
<td id="T_31fd7_row8_col4" class="data row8 col4">10.888</td>
<td id="T_31fd7_row8_col5" class="data row8 col5">4022</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>The summary statistics table shows obvious differences in return, measured here as mean daily return (%) and volatility, as standard deviation. Technology (XLK) has the highest mean daily return at 0.078%, and close second is Consumer Discretionary (XLY) at 0.065%. We identified this trend above as well when we looked at cumulative returns. At the same time, both sectors were relatively volatile, with XLK at 1.369 and XLY at 1.281. In simple terms, a standard deviation of 1.369 suggests that XLK’s daily return was typically about 1.4 percentage points away from its average daily return, indicating a much less stable return pattern. Energy (XLE) stands out the most as it has the worst mean daily return at 0.035%, combined with the highest volatility reported at 1.718 and also the worst single day loss at an impressive -20.141%. This makes Energy the weakest sector in terms of long-run growth and return to risk. By contrast, Consumer Staples (XLP) and Health Care (XLV) show much lower volatility, although this came with more modest average returns. This suggests that these sectors may have offered more stable, but less rewarding, investment profiles over the period.</p>
</section>
<section id="volatility-comparison" class="level4">
<h4 class="anchored" data-anchor-id="volatility-comparison">Volatility Comparison</h4>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="output/figures/volatility_comparison.png" class="img-fluid figure-img"></p>
<figcaption>Volatility Comparison of SPY and Major U.S. Sector ETFs, 2010 to 2025.</figcaption>
</figure>
</div>
<p>Annualised volatility shows how much a sector’s returns typically fluctuate over a year, so a higher value indicates a less stable return pattern. This graph makes the differences in risk even clearer. Energy (XLE) had the highest annualised volatility of more than 27%, which confirms that the ETF was much less stable than the others. Financials (XLF) and Technology (XLK) also had somewhat higher volatility, however this came with a stronger return. SPY, the project benchmark, had an annualised volatility of around 17%, which places it near the middle of the distribution. This suggests that the broader market offered a more balanced risk profile than the most aggressive sector ETFs, while still being less defensive than sectors such as Health Care (XLV) and Consumer Staples (XLP). XLV’s annualised volatility was 16.2, and XLP’s was 13.7. A likely reason why XLP and XLV recorded the lowest volatility is that both are commonly considered defensive sectors, with demand that is less sensitive to changes in the wider economic cycle; people will always need essential consumer goods and health-related services in any economic period. An interesting point to note is that XLV has the second-lowest annualised volatility and standard deviation, yet it finished 3 highest out of the ETFs in terms of cumulative return.<br>
</p>
</section>
</section>
<section id="correlation-and-diversification" class="level3">
<h3 class="anchored" data-anchor-id="correlation-and-diversification">Correlation and Diversification</h3>
<p>Correlation is a useful indicator to look at because it measures how much returns move together between sectors. A higher correlation means two sectors tend to rise and fall in similar ways, a lower correlation suggests that their returns are more distinct and don’t move with each other. This may offer more diversification benefits.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="output/figures/correlation_heatmap.png" class="img-fluid figure-img"></p>
<figcaption>Correlation heatmap of daily returns for SPY and major U.S. sector ETFs.</figcaption>
</figure>
</div>
<p>The heatmap shows that all sectors were positively correlated with each other, meaning the sector ETFs moved together. The strongest correlations are between the market benchmark (SPY) and Technology (XLK), at 0.925, and between SPY and Consumer Discretionary (XLY) at 0.908. This high correlation means that Consumer Discretionary and Technology moved nearly identically to the market benchmark. This is likely because XLK and XLY make up 35% and 10%, respectively, of the SPY sector allocation. By contrast, Energy (XLE) and Utilities (XLU) recorded the lowest correlation at 0.407, suggesting that they behaved more differently from one another than any other pair of sectors in the sample. As a whole, Energy and Utilities tend to show weaker correlations with the rest of the market, which gives some opportunity for diversification. However, because all correlations remained positive and many were still relatively high, the evidence suggests that sector diversification reduced risk only to a limited extent rather than creating fully independent return patterns.</p>
</section>
<section id="market-beta-and-market-exposure" class="level3">
<h3 class="anchored" data-anchor-id="market-beta-and-market-exposure">Market beta and market exposure</h3>
<p>Market beta measures how sensitive a sector’s returns are to movements in the broader market. A beta above 1 suggests that a sector tends to move more than the market, while a beta below 1 indicates a less sensitive or more defensive return pattern.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="output/figures/market_beta_chart.png" class="img-fluid figure-img"></p>
<figcaption>Market beta for each sector ETF relative to SPY.</figcaption>
</figure>
</div>
<p>The chart confirms several patterns seen above. Technology (XLK) once again stands out, with a beta of 1.168, making it the most sensitive to movements in the overall market. Financials (XLF) ranks second with a beta of 1.108, which is interesting because its cumulative return was much less exceptional than that of XLK or XLY. This suggests that high market sensitivity does not automatically translate into the strongest long-run performance. Energy (XLE), Consumer Discretionary (XLY), and Materials (XLB) also recorded beta values above 1, indicating that these sectors tended to amplify market movements. By comparison, Health Care (XLV), Utilities (XLU), and Consumer Staples (XLP) all had beta values below 1, which supports the earlier view that these sectors behaved more defensively over the sample period. Consumer Staples (XLP) had the lowest beta at 0.584, implying that it was the least exposed to market-wide swings. Overall, the bar chart shows that the sector differences weren’t just about return and volatility, but also about how strongly each sector responded to changes in the market.</p>
<section id="regression-results" class="level4">
<h4 class="anchored" data-anchor-id="regression-results">Regression results</h4>
<div id="62e7877e" class="cell" data-execution_count="2">
<div class="cell-output cell-output-display" data-execution_count="6">
<style type="text/css">
</style>

<table id="T_3fc3d" class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th id="T_3fc3d_level0_col0" class="col_heading level0 col0" data-quarto-table-cell-role="th">Ticker</th>
<th id="T_3fc3d_level0_col1" class="col_heading level0 col1" data-quarto-table-cell-role="th">Alpha</th>
<th id="T_3fc3d_level0_col2" class="col_heading level0 col2" data-quarto-table-cell-role="th">Beta</th>
<th id="T_3fc3d_level0_col3" class="col_heading level0 col3" data-quarto-table-cell-role="th">R²</th>
<th id="T_3fc3d_level0_col4" class="col_heading level0 col4" data-quarto-table-cell-role="th">p-value-alpha</th>
<th id="T_3fc3d_level0_col5" class="col_heading level0 col5" data-quarto-table-cell-role="th">p-value-beta</th>
<th id="T_3fc3d_level0_col6" class="col_heading level0 col6" data-quarto-table-cell-role="th">Observations</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td id="T_3fc3d_row0_col0" class="data row0 col0">XLK</td>
<td id="T_3fc3d_row0_col1" class="data row0 col1">0.010</td>
<td id="T_3fc3d_row0_col2" class="data row0 col2">1.168</td>
<td id="T_3fc3d_row0_col3" class="data row0 col3">0.855</td>
<td id="T_3fc3d_row0_col4" class="data row0 col4">0.226</td>
<td id="T_3fc3d_row0_col5" class="data row0 col5">0</td>
<td id="T_3fc3d_row0_col6" class="data row0 col6">4022</td>
</tr>
<tr class="even">
<td id="T_3fc3d_row1_col0" class="data row1 col0">XLF</td>
<td id="T_3fc3d_row1_col1" class="data row1 col1">-0.009</td>
<td id="T_3fc3d_row1_col2" class="data row1 col2">1.108</td>
<td id="T_3fc3d_row1_col3" class="data row1 col3">0.755</td>
<td id="T_3fc3d_row1_col4" class="data row1 col4">0.385</td>
<td id="T_3fc3d_row1_col5" class="data row1 col5">0</td>
<td id="T_3fc3d_row1_col6" class="data row1 col6">4022</td>
</tr>
<tr class="odd">
<td id="T_3fc3d_row2_col0" class="data row2 col0">XLE</td>
<td id="T_3fc3d_row2_col1" class="data row2 col1">-0.024</td>
<td id="T_3fc3d_row2_col2" class="data row2 col2">1.078</td>
<td id="T_3fc3d_row2_col3" class="data row2 col3">0.463</td>
<td id="T_3fc3d_row2_col4" class="data row2 col4">0.230</td>
<td id="T_3fc3d_row2_col5" class="data row2 col5">0</td>
<td id="T_3fc3d_row2_col6" class="data row2 col6">4022</td>
</tr>
<tr class="even">
<td id="T_3fc3d_row3_col0" class="data row3 col0">XLY</td>
<td id="T_3fc3d_row3_col1" class="data row3 col1">0.003</td>
<td id="T_3fc3d_row3_col2" class="data row3 col2">1.073</td>
<td id="T_3fc3d_row3_col3" class="data row3 col3">0.824</td>
<td id="T_3fc3d_row3_col4" class="data row3 col4">0.741</td>
<td id="T_3fc3d_row3_col5" class="data row3 col5">0</td>
<td id="T_3fc3d_row3_col6" class="data row3 col6">4022</td>
</tr>
<tr class="odd">
<td id="T_3fc3d_row4_col0" class="data row4 col0">XLB</td>
<td id="T_3fc3d_row4_col1" class="data row4 col1">-0.018</td>
<td id="T_3fc3d_row4_col2" class="data row4 col2">1.040</td>
<td id="T_3fc3d_row4_col3" class="data row4 col3">0.740</td>
<td id="T_3fc3d_row4_col4" class="data row4 col4">0.081</td>
<td id="T_3fc3d_row4_col5" class="data row4 col5">0</td>
<td id="T_3fc3d_row4_col6" class="data row4 col6">4022</td>
</tr>
<tr class="even">
<td id="T_3fc3d_row5_col0" class="data row5 col0">XLV</td>
<td id="T_3fc3d_row5_col1" class="data row5 col1">0.007</td>
<td id="T_3fc3d_row5_col2" class="data row5 col2">0.768</td>
<td id="T_3fc3d_row5_col3" class="data row5 col3">0.668</td>
<td id="T_3fc3d_row5_col4" class="data row5 col4">0.438</td>
<td id="T_3fc3d_row5_col5" class="data row5 col5">0</td>
<td id="T_3fc3d_row5_col6" class="data row5 col6">4022</td>
</tr>
<tr class="odd">
<td id="T_3fc3d_row6_col0" class="data row6 col0">XLU</td>
<td id="T_3fc3d_row6_col1" class="data row6 col1">0.010</td>
<td id="T_3fc3d_row6_col2" class="data row6 col2">0.598</td>
<td id="T_3fc3d_row6_col3" class="data row6 col3">0.346</td>
<td id="T_3fc3d_row6_col4" class="data row6 col4">0.456</td>
<td id="T_3fc3d_row6_col5" class="data row6 col5">0</td>
<td id="T_3fc3d_row6_col6" class="data row6 col6">4022</td>
</tr>
<tr class="even">
<td id="T_3fc3d_row7_col0" class="data row7 col0">XLP</td>
<td id="T_3fc3d_row7_col1" class="data row7 col1">0.007</td>
<td id="T_3fc3d_row7_col2" class="data row7 col2">0.584</td>
<td id="T_3fc3d_row7_col3" class="data row7 col3">0.537</td>
<td id="T_3fc3d_row7_col4" class="data row7 col4">0.426</td>
<td id="T_3fc3d_row7_col5" class="data row7 col5">0</td>
<td id="T_3fc3d_row7_col6" class="data row7 col6">4022</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
</section>
</section>
<section id="conclusion" class="level2">
<h2 class="anchored" data-anchor-id="conclusion">Conclusion</h2>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>